In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)

In [3]:
a.shape,a.dtype,a.size,a.itemsize,a.ndim,a.data

((3, 4), dtype('int32'), 12, 4, 2, <memory at 0x000001ED7FDE2708>)

ndarray.itemsize: the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

In [4]:
# create array
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([[1, 2, 3], [4, 5, 6]])
c = np.array([[1, 2], [3, 4]], dtype=complex)
a, b, c

(array([1, 2, 3, 4, 5, 6]), array([[1, 2, 3],
        [4, 5, 6]]), array([[1.+0.j, 2.+0.j],
        [3.+0.j, 4.+0.j]]))

In [5]:
a = np.zeros((3, 4))
b = np.ones((2, 3))
c = np.empty((4, 5))
d = np.zeros_like(c)
a, b, c, d

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[1., 1., 1.],
        [1., 1., 1.]]), array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
         7.56571288e-307, 1.89146896e-307],
        [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
         1.78020169e-306, 7.56601165e-307],
        [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
         1.69119330e-306, 1.02360867e-306],
        [1.60220528e-306, 1.78019082e-306, 9.34598925e-307,
         7.56602523e-307, 1.69121096e-306]]), array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [6]:
# rcreate sequences
a = np.arange(0, 2, 0.5)
b = np.linspace(0, 2, 5)
c = np.arange(12).reshape(3, 4)
a, b, c

(array([0. , 0.5, 1. , 1.5]),
 array([0. , 0.5, 1. , 1.5, 2. ]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [7]:
# np.set_printoptions(threshold=np.nan)
# #当numpy数据过多无法完全显示时，使用这条函数限定打印出来的大小
np.set_printoptions(threshold=10)

In [8]:
# np.random
a = np.random.rand(4, 2)
'''
rand函数根据给定维度生成[0,1)之间的数据，包含0，不包含1
dn表格每个维度
返回值为指定维度的array
'''
b = np.random.randn(4)
'''
randn函数返回一个或一组样本，具有标准正态分布。
'''
c = np.random.randint(0, 12, size=(3, 4), dtype=int)
'''
返回随机整数，范围区间为[low,high），包含low，不包含high
参数：low为最小值，high为最大值，size为数组维度大小，dtype为数据类型，默认的数据类型是np.int
high没有填写时，默认生成随机数的范围是[0，low)
'''
d = np.random.random(size=(3, 4))
# 生成0,1之间的随机浮点数
# np.random.seed(5)
# 设置随机种子，当种子数相同时，得到的随机数固定
a, b, c, d

(array([[0.29318721, 0.65866892],
        [0.51826153, 0.19749455],
        [0.19840152, 0.10965068],
        [0.1052826 , 0.85628338]]),
 array([1.78473733, 0.16767122, 0.07145335, 1.32466683]),
 array([[ 3,  7, 10,  5],
        [11,  8,  5,  6],
        [ 2, 11,  3,  0]]),
 array([[0.4526732 , 0.030455  , 0.03947852, 0.81692369],
        [0.91512298, 0.48444875, 0.75324191, 0.64990661],
        [0.34567689, 0.5861805 , 0.54351921, 0.14699092]]))

In [9]:
# 索引和切片
a = np.arange(12)
# a[:6:2]=100
# 在0到6之间，每隔两个就赋值为100
a[1], a[1:3], a[::-1]

(1, array([1, 2]), array([11, 10,  9, ...,  2,  1,  0]))

In [10]:
def f(x, y):
    return x*y


a = np.fromfunction(f, (4, 5), dtype=int)
a

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [11]:
a[1, 2], a[:, 1], a[1:3, 1], a[1:3, 1:3], a[-1]

(2, array([0, 1, 2, 3]), array([1, 2]), array([[1, 2],
        [2, 4]]), array([ 0,  3,  6,  9, 12]))

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].

In [12]:
a = np.arange(12)
a.resize((2, 6))
a, a.reshape(3, 4)
'''
reshape的维度出现-1时，需要根据另外一个维度参数进行自适应
'''

'\nreshape的维度出现-1时，需要根据另外一个维度参数进行自适应\n'

In [13]:
a = np.floor(10*np.random.random((2, 12)))
b = np.hsplit(a, 3)   # Split a into 3
c = np.hsplit(a, (3, 4))   # Split a after the third and the fourth column
a, d, c

(array([[2., 7., 8., ..., 5., 1., 8.],
        [2., 7., 8., ..., 1., 5., 8.]]),
 array([[0.4526732 , 0.030455  , 0.03947852, 0.81692369],
        [0.91512298, 0.48444875, 0.75324191, 0.64990661],
        [0.34567689, 0.5861805 , 0.54351921, 0.14699092]]),
 [array([[2., 7., 8.],
         [2., 7., 8.]]), array([[6.],
         [8.]]), array([[5., 7., 5., ..., 5., 1., 8.],
         [0., 7., 7., ..., 1., 5., 8.]])])

In [15]:
a = np.array((1, 2, 3, 4, 5, 6))
b = a
b[1] = 0
id(a), id(b), a, b, b is a
# 非复制，都指向与相同的数据对象

(1956653373360,
 1956653373360,
 array([1, 0, 3, 4, 5, 6]),
 array([1, 0, 3, 4, 5, 6]),
 True)

In [14]:
a = np.array((1, 2, 3, 4, 5, 6))
b = a.view()
b[0] = 0
b.reshape(2, 3)
a, b, a.shape, b.shape, b is a
# 对象b和a都可以对数据的数值进行修改，
# 但是b不能对a.shape属性进行修改。

(array([0, 2, 3, 4, 5, 6]), array([0, 2, 3, 4, 5, 6]), (6,), (6,), False)

In [16]:
a = np.array((1, 2, 3, 4, 5, 6))
b = a.copy()
b[0] = 0
b.reshape(2, 3)
a, b, a.shape, b.shape, b is a
# 深复制，新建一个数据对象

(array([1, 2, 3, 4, 5, 6]), array([0, 2, 3, 4, 5, 6]), (6,), (6,), False)

### Functions and Methods Overview

Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

#### Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
#### Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
#### Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
#### Questions
all, any, nonzero, where
#### Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
#### Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
#### Basic Statistics
cov, mean, std, var
#### Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot

In [19]:
a = np.arange(6)**2
i = np.array([1, 1, 3, 2, 5])
j = np.array([[1, 2], [3, 4]])
a[i], a[j]

(array([ 1,  1,  9,  4, 25], dtype=int32), array([[ 1,  4],
        [ 9, 16]], dtype=int32))

In [20]:
img = np.array([
    [0, 0, 0],
    [255, 0, 0],
    [0, 255, 255],
    [0, 0, 255],
    [255, 255, 255]
])
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])
img[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255, 255],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [21]:
a = np.arange(12).reshape(3, 4)
i = np.array([[0, 1],# indices for the first dim of a
              [1, 2]])
j = np.array([[2, 1], # indices for the second dim
              [3, 3]])

a[i, j],a[i, 2],a[:, j]# i and j must have equal shape
# i.e., a[ : , j]

(array([[ 2,  5],
        [ 7, 11]]), array([[ 2,  6],
        [ 6, 10]]), array([[[ 2,  1],
         [ 3,  3]],
 
        [[ 6,  5],
         [ 7,  7]],
 
        [[10,  9],
         [11, 11]]]))

In [23]:
a = np.arange(12).reshape(3,4)
b = a > 4
a, a[b]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([ 5,  6,  7,  8,  9, 10, 11]))

In [24]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])
b2 = np.array([True,False,True,False])
a[b1,:],a[b1],a[:,b2],a[b1,b2]

(array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[ 0,  2],
        [ 4,  6],
        [ 8, 10]]), array([ 4, 10]))

In [25]:
a = np.arange(0,10,2)
b = np.arange(5)
x = np.vstack([a,b])
y = np.hstack([a,b])
x,y

(array([[0, 2, 4, 6, 8],
        [0, 1, 2, 3, 4]]), array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4]))